spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost/fm
    username: root
    password: root

---
spring:
  profiles: development
logging:
  level: debug
---
spring:
  profiles: production

logging:
  level: error
